### ISSUE TITLE
Fix all console warnings

### ISSUE THREAD

**Issue by raae** [olavea/unlockopen.com#8]
Yes, I mean all before doing anything else.

**Comment by olavea** [comment]
deleted ", scale" from components/BasicLayout.js

 WARNING  Compiled with 14 warnings                                              11:01:34 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/BasicLayout.js
  8:18  warning  'scale' is defined but never used

**Comment by olavea** [comment]
// import { MIN_DEFAULT_MEDIA_QUERY } from "typography-breakpoint-constants";

WARNING  Compiled with 13 warnings                                              11:04:00 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/Bio/index.js
   5:10  warning  'MIN_DEFAULT_MEDIA_QUERY' is defined but never used

**Comment by olavea** [comment]
```
<span role="img" aria-label="envelope">
              ✉️ <a href="mailto:blabla@blabla.com">blabla@blabla.com</a>
            </span>

```
in components/Bio/index.js
 
### got inspiration from storybook, thanks [@Hypnosphi](https://github.com/Hypnosphi) 
[https://github.com/storybookjs/storybook/pull/3011/commits/e5b73a3d73d5b9251e8386ab3226d73564ecbc81
](https://github.com/storybookjs/storybook/pull/3011/commits/e5b73a3d73d5b9251e8386ab3226d73564ecbc81
)
WARNING  Compiled with 13 warnings                                              11:05:39 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/Bio/index.js
  61:11  warning  Emojis should be wrapped in <span>, have role="img", and have an accessibl
e description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

**Comment by olavea** [comment]
// import Link from "gatsby-link";
in components/ColorLine.js

WARNING  Compiled with 12 warnings                                              11:17:10 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/ColorLine.js
  2:8  warning  'Link' is defined but never used  no-unused-vars

**Comment by olavea** [comment]
// import Link from "gatsby-link";
//    const style = this.props.style;
in /components/brand../Scale.js

**Comment by olavea** [comment]
```
// import Link from "gatsby-link";
// import { rhythm } from "../utils/typography";

```
in src/components/Footer.js

 WARNING  Compiled with 11 warnings                                              11:18:31 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/Footer.js
  2:8   warning  'Link' is defined but never used    no-unused-vars
  3:10  warning  'rhythm' is defined but never used  no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

**Comment by olavea** [comment]
`
// import { rhythm, scale } from "../utils/typography";
`
in src/components/Layout.js⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/Layout.js
  7:10  warning  'rhythm' is defined but never used  no-unused-vars
  7:18  warning  'scale' is defined but never used   no-unused-vars

**Comment by olavea** [comment]
```
// import Link from "gatsby-link";
// import { rhythm } from "../utils/typography";
// import css from "./mailinglist-form.css";

```
in src/components/MailinglistForm.js
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/MailinglistForm.js
  2:8   warning  'Link' is defined but never used    no-unused-vars
  3:10  warning  'rhythm' is defined but never used  no-unused-vars
  4:8   warning  'css' is defined but never used     no-unused-vars

**Comment by olavea** [comment]
`const scale = this.props.scale === "";`
in ...guidelines/Color.js
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/brand-guidelines/Color.js
  11:36  warning  Expected '===' and instead saw '=='  eqeqeq

✖ 1 problem (0 errors, 1 warning)

⠀

**Comment by olavea** [comment]
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/brand-guidelines/Font.js
  2:8  warning  'Link' is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)

⠀

**Comment by olavea** [comment]
```
import React from "react";
// import Link from "gatsby-link";
import { rhythm } from "../../utils/typography";

class Scale extends React.Component {
  render() {
    //    const style = this.props.style;
```



in src/components/brand-guidelines/Scale.js
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/brand-guidelines/Scale.js
  2:8   warning  'Link' is defined but never used            no-unused-vars
  7:11  warning  'style' is assigned a value but never used  no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

**Comment by olavea** [comment]
Now I decided to DELETE code
```

import Link from "gatsby-link";
...
const colors = brand.COLOR_PRIMARY;
    const logoStyles = {
      height: rhythm(5),
      width: rhythm(5),
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    };

```

in src/pages/brand-guidelines.js

success start webpack server - 0.870 s — 1/1 7.47 pages/second
 WARNING  Compiled with 4 warnings                                               11:32:37 AM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/pages/brand-guidelines.js
  10:8   warning  'Link' is defined but never used                 no-unused-vars
  18:11  warning  'colors' is assigned a value but never used      no-unused-vars
  19:11  warning  'logoStyles' is assigned a value but never used  no-unused-vars

✖ 3 problems (0 errors, 3 warnings)

**Comment by olavea** [comment]
deleted

```

import { rhythm, scale, options } from "../utils/typography";
import * as brand from "../utils/brand";

```
in /src/pages/info.js⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/pages/info.js
  5:10  warning  'rhythm' is defined but never used   no-unused-vars
  5:18  warning  'scale' is defined but never used    no-unused-vars
  5:25  warning  'options' is defined but never used  no-unused-vars
  6:13  warning  'brand' is defined but never used    no-unused-vars

✖ 4 problems (0 errors, 4 warnings)

**Comment by olavea** [comment]
```
deleted

import ms from "modularscale";
  COLOR_SECONDARY,
  COLOR_TERTIARY,
  COLOR_QUARTERLY,
  COLOR_BACKGROUND,

    const alternate = {
      ...adjustFontSizeTo(small),
      fontFamily: bodySerifFont,
      fontWeight: 400,
    };
```

in src/utils/typography.js
/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/utils/typography.js
   2:8   warning  'ms' is defined but never used                  no-unused-vars
   7:3   warning  'COLOR_SECONDARY' is defined but never used     no-unused-vars
   8:3   warning  'COLOR_TERTIARY' is defined but never used      no-unused-vars
   9:3   warning  'COLOR_QUARTERLY' is defined but never used     no-unused-vars
  10:3   warning  'COLOR_BACKGROUND' is defined but never used    no-unused-vars
  70:11  warning  'alternate' is assigned a value but never used  no-unused-vars

**Comment by olavea** [comment]
`const bodySerifFont = textify(["Merriweather", "serif"]);`

in src/utils/typography.js
WARNING  Compiled with 2 warnings                                               12:20:27 PM
⠀
Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/utils/typography.js
  57:11  warning  'bodySerifFont' is assigned a value but never used  no-unused-vars

✖ 1 problem (0 er

**Comment by olavea** [comment]
deleted
import Hero from './Hero'
import { rhythm, scale } from "../utils/typography";

Changed to
```

...
    const childrenOfMatryoshka  = this.props.children;
    let layoutBio = this.props.bio ? <Bio /> : null;
...
        {childrenOfMatryoshka}
        {layoutBio}


```
 warning  in ./src/components/Layout.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/node_modules/eslint-loader/index.js??ref--11-0!/Users/olavea/Desktop/Develop/forClients/Tobie/3.0_Tobie/src/components/Layout.js

**Comment by olavea** [comment]
Compiled with 1 warnings    

success start webpack server - 0.872 s — 1/1 7.18 pages/second
 WARNING  Compiled with 1 warnings                                               12:31:53 PM
⠀
 warning  in ./src/components/Layout.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

**Comment by raae** [comment]
I fixed the last warning, changed `import Layout from "../components/layout";` to `import Layout from "../components/Layout";`.

Lowercase `l` to uppercase `L`.
