### ISSUE TITLE
Run prettier on all code

### ISSUE THREAD

**Issue by raae** [olavea/unlockopen.com#9]
Run the command `yarn format` and all files will be changed to the configured prettier style.

This is important so moving forward we only see code changes in Pull Requests and not format changes.

**Comment by olavea** [comment]
Check

**Comment by olavea** [comment]
git commit -a -m "yarn format"
git push
see [https://github.com/olavea/unlockopen.com/pull/3](https://github.com/olavea/unlockopen.com/pull/3)
